name: live_streaming_cohost
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.2.0+1

environment:
  sdk: ">=2.16.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  zego_uikit: ^2.15.8
  zego_uikit_prebuilt_live_streaming: ^2.25.0
  zego_uikit_signaling_plugin: ^2.7.3

  cupertino_icons: ^1.0.2
  flutter_screenutil: ">=5.5.3+2 <5.6.1"
  cached_network_image: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  dart_code_metrics: any

flutter:
  uses-material-design: true
