name: live_streaming_cohost
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.2.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  zego_uikit: ^2.5.7
  zego_uikit_prebuilt_live_streaming: ^2.5.10
  zego_uikit_signaling_plugin: ^2.1.5

  cupertino_icons: ^1.0.2
  flutter_screenutil: ">=5.5.3+2 <5.6.1"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  dart_code_metrics: any

flutter:
  uses-material-design: true
